server:
  port: 8095
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:certificate.p12
#    key-store-password: 1234

spring:
  application:
    name: spring-security-application
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 1234
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
